---

- name: Ensure that includes dir exists
  file:
    path: "{{ nginx_includes_path }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"

- name: Copy role include files
  copy:
    src: "includes/"
    dest: "{{ nginx_includes_path }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  notify: reload nginx

- name: Create extra includes from config
  copy:
    content: "{{ item.value }}"
    dest: "{{ nginx_includes_path }}/{{ item.key }}.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  with_dict: "{{ nginx_includes_extra }}"
  notify: reload nginx

- name: Create extra includes from templates
  template:
    src: "{{ item }}"
    dest: "{{ nginx_includes_path }}/{{ item | basename | regex_replace('\\.j2','') }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  with_items: "{{ nginx_includes_extra_templates }}"
  notify: reload nginx
